config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :patients

  root 'welcome#index'
  get 'users/sign_up'
  get 'users/sign_in'
  get 'patients/index'

  devise_scope :user do
    get 'users/sign_out' => 'devise/sessions#destroy'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user

  def self.search(search)
    if search
      where(["surname || forename LIKE ?", "%#{search}%"])
    else
      all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :patients
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, except: [:index, :show] #user is routed to sign up page when not logged in
  helper_method :sort_column, :sort_direction

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = current_user.patients.build
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = current_user.patients.build(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:forename, :surname, :date_of_birth, :address, :phone_number, :infection_or_injury, :symptoms, :other_observations)
    end

    # Accessor methods to sort columns. Default is ascending order by surnames
    def sort_column
      Patient.column_names.include?(params[:sort]) ? params[:sort] : "surname"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if user_signed_in?
      redirect_to patients_path
    else
      render action: "index"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortColumn(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
  <nav class="navbar navbar-inverse" role="navigation">
    <div class="container">
      <div class="navabr-header">
        <%= link_to "Smart Healthcare Hub", root_path, class: "navbar-brand" %>
      </div>

      <!-- links -->
      <div class="collapse navbar-collapse navbar-right" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <% if user_signed_in? %>
            <li> <%= link_to "New Patient", new_patient_path, class: "active" %> </li>
            <li> <%= link_to "My Account", edit_user_registration_path %> </li>
            <li> <%= link_to "Log Out", destroy_user_session_path, method: :delete %> </li>
          <% else %>
            <li> <%= link_to "Register", new_user_registration_path, class: "active" %> </li>
            <li> <%= link_to "Log In", new_user_session_path, class: "active" %> </li>
          <% end %>
        </ul>
        <!-- search textfield -->
        <form class="navbar-form navbar-right" role="search">
          <div class="form-group">
            <%= form_tag patients_path, :method => 'get' do %>
              <%= text_field_tag :search, params[:search], class: "form-control" %>
              <%= submit_tag "Search", :name => nil, class: "btn btn-default" %>
            <% end %>
          </div>
        </form>
      </div>
    </div>
  </nav>
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smart Healthcare Hub</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<div class="container form-group-lg ">

    <%= form_with(model: patient, local: true) do |form| %>
      <% if patient.errors.any? %>
        <div id="error_explanation">
          <<h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

          <ul>
          <% patient.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :forename %>
        <%= form.text_field :forename, id: :patient_forename, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :surname %>
        <%= form.text_field :surname, id: :patient_surname, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :date_of_birth %>
        <%= form.date_select :date_of_birth,  { :include_blank => true, :start_year => 1900 } , id: :patient_date_of_birth, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_field :address, id: :patient_address, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :phone_number %>
        <%= form.text_field :phone_number, id: :patient_phone_number, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :infection_or_injury %>
        <%= form.text_field :infection_or_injury, id: :patient_infection_or_injury, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :symptoms %>
        <%= form.text_area :symptoms, id: :patient_symptoms, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :other_observations %>
        <%= form.text_area :other_observations, id: :patient_other_observations, class: "form-control" %>
      </div>

      <div class="actions" align="center">
        <%= form.submit "Save", class: "btn btn-primary btn-lg" %>
        <%= link_to "Back", patients_path, class: "btn btn-primary btn-lg" %>
      </div>
    <% end %>

</div>

app/views/patients/edit.html.erb
<center><h1>Editing Patient</h1></center>

<%= render 'form', patient: @patient %><br/>

app/views/patients/index.html.erb
<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th><%= sortColumn "forename" %></th>
      <th><%= sortColumn "surname" %></th>
      <th>Date of Birth</th>
      <th>Address</th>
      <th>Phone Number</th>
      <th>Infection or Injury</th>
      <th>Symptoms</th>
      <th>Other Observations</th>
      <th>Added By:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.forename %></td>
        <td><%= patient.surname %></td>
        <td><%= patient.date_of_birth %></td>
        <td><%= patient.address %></td>
        <td><%= patient.phone_number %></td>
        <td><%= patient.infection_or_injury %></td>
        <td><%= patient.symptoms %></td>
        <td><%= patient.other_observations %></td>
        <td><%= patient.user.email %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Continue to Delete Patient?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @patients %>

app/views/patients/new.html.erb
<center><h1>New Patient</h1></center>

<%= render 'form', patient: @patient %><br/>

app/views/patients/show.html.erb
<div class="container" id="showPatient">
    <p>
      <strong>Forename:</strong>
      <%= @patient.forename %>
    </p>

    <p>
      <strong>Surname:</strong>
      <%= @patient.surname %>
    </p>

    <p>
      <strong>Date of birth:</strong>
      <%= @patient.date_of_birth %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @patient.address %>
    </p>

    <p>
      <strong>Phone number:</strong>
      <%= @patient.phone_number %>
    </p>

    <p>
      <strong>Infection or injury:</strong>
      <%= @patient.infection_or_injury %>
    </p>

    <p>
      <strong>Symptoms:</strong>
      <%= @patient.symptoms %>
    </p>

    <p>
      <strong>Other observations:</strong>
      <%= @patient.other_observations %>
    </p>
</div>
<br/>
<div class="actions" align="center">
  <%= link_to "Edit", edit_patient_path(@patient), class: "btn btn-primary btn-lg" %>
  <%= link_to "Back", patients_path, class: "btn btn-primary btn-lg" %>
</div><br/>

app/views/welcome/index.html.erb
<br/>
<center>
  <h1>Welcome to Smart Healthcare Hub!</h1>
  <h3>A simple, easy and organized management system for all medical services.</h3>
  <%= image_tag "icon.png" %>
</center>